### ISSUE TITLE
Investigate signature issues

### ISSUE THREAD

**Issue by hbmartin** [hbmartin/pytube3#9]
See:
https://github.com/nficano/pytube/pull/352/files
https://github.com/irfancnk/pytube/commit/56a802454bd2d9820b06c9177f3cc8aaba9182ab
https://github.com/nficano/pytube/pull/426/files
https://github.com/nficano/pytube/pull/427/files

**Comment by swiftyy-mage** [comment]
Just from going over the code in https://github.com/nficano/pytube/pull/352/files , it would not even fix the hypothetical issue. It would have just raised a more informative exception and made a log of it, but the video would still not have been downloaded (I think). I can't explain why people were saying they were getting regex errors, in the comments for that commit. But just look at the code and you will see what I mean. Not aware of any current issue.

irfancnk@56a8024 simply makes the code more readable, but it is executed exactly the same.

https://github.com/nficano/pytube/pull/426/files just increases the range of conditions to trigger skipping the `apply_signature` function. It has since been improved even more to include a wider range of conditions, and I am not aware of any issue with it. 

The last two pull requests you linked are about an old issue, people were getting 403 errors trying to download most videos. One of the things required to fix it was to include `headers={"User-Agent": "Mozilla/5.0"}` in the GET request to trick youtube into thinking that pytube is a web browser, instead up it just saying 'Hey guys! Python here! Data please?'. They also changed a few other things but I wouldn't worry about it, people fixed them. YouTube are always changing how their site works slightly.

**Comment by movraxrsp** [comment]
> Just from going over the code in https://github.com/nficano/pytube/pull/352/files , it would not even fix the hypothetical issue. It would have just raised a more informative exception and made a log of it, but the video would still not have been downloaded (I think). I can't explain why people were saying they were getting regex errors, in the comments for that commit. But just look at the code and you will see what I mean. Not aware of any current issue.

Agreed. There are also no URLs for test cases in the comments in [Issue 347](https://github.com/nficano/pytube/issues/347). Then the PR does nothing to handle the 's' key error. So 347/352 seems like a dead-end.

**Comment by movraxrsp** [comment]
> [irfancnk/pytube@56a8024](https://github.com/irfancnk/pytube/commit/56a8024) simply makes the code more readable, but it is executed exactly the same

Agreed, only moving ()s and whitespace around.

**Comment by movraxrsp** [comment]
I see a _potential_ case for [mixins:56](https://github.com/hbmartin/pytube3/blob/79a94b4e2b5764d3db30d5bafb2ec0d8eae4e847/pytube/mixins.py#L56) throwing a `KeyError`.

Suppose `signature`, `s`, `&sig`, and `&lsig` do not exist and `js` does exist.

Then execution falls from the `if` in [mixins:46](https://github.com/hbmartin/pytube3/blob/79a94b4e2b5764d3db30d5bafb2ec0d8eae4e847/pytube/mixins.py#L46), to line 55. Then `stream['s']` in line 56 generates an unhandled `KeyError`.

It may be unlikely, but it is possible for YouTube makes a change such that this case occurs.

I spent some time call tracing to see if somewhere in the call stack this `KeyError` would be handled, but I did not see where it would be. I don't have time to continue checking further now.

Regardless, adding a check in line 55 should make the code more bulletproof: `if 's' in stream and js is not None:`

**Comment by hbmartin** [comment]
Thanks for this insight. I think I'll close this issue for now since there don't seem to be any actual outstanding problems to address here. If `s` doesn't exist I'd rather get an issue with trace/url to do an actual investigation. Sound good?

**Comment by movraxrsp** [comment]
Sure.
